EMOTE_DICT = {
    "Rest": ["sit-idle-cute", 20.0],
    "Timejump": ["emote-timejump", 4.01],
    "Hearteyes": ["emote-hearteyes", 4.03],
    "Snake": ["emote-snake", 5.26],
    "Zombie": ["idle_zombie", 28.75],
    "Relaxed": ["idle_layingdown2", 15.0],
    "Attentive": ["idle_layingdown", 24.58],
    "Pouty Face": ["idle-sad", 24.38],
    "Posh": ["idle-posh", 21.85],
    "Sleepy": ["idle-loop-tired", 21.96],
    "Tap Loop": ["idle-loop-tapdance", 6.26],
    "Blowing A Kiss": ["emote-kiss", 2.39],
    "Sit": ["idle-loop-sitfloor", 22.32],
    "Shy Loop": ["idle-loop-shy", 15.0],
    "Bummed": ["idle-loop-sad", 6.05],
    "Chillin'": ["idle-loop-happy", 18.8],
    "Annoyed": ["idle-loop-annoyed", 17.06],
    "Aerobics": ["idle-loop-aerobics", 8.51],
    "Ponder": ["idle-lookup", 22.34],
    "Hero Pose": ["idle-hero", 21.88],
    "Relaxing": ["idle-floorsleeping2", 17.25],
    "Cozy Nap": ["idle-floorsleeping", 13.94],
    "Astronaut": ["emote-astronaut", 13.79],
    "Enthused": ["idle-enthusiastic", 15.94],
    "Boogie Swing": ["idle-dance-swinging", 13.2],
    "Feel The Beat": ["idle-dance-headbobbing", 25.37],
    "Irritated": ["idle-angry", 25.43],
    "Yes": ["emote-yes", 2.57],
    "I Believe I Can Fly": ["emote-wings", 13.13],
    "The Wave": ["emote-wave", 2.69],
    "Tired": ["emote-tired", 4.61],
    "Think": ["emote-think", 3.69],
    "Theatrical": ["emote-theatrical", 8.59],
    "Tap Dance": ["emote-tapdance", 11.06],
    "Super Run": ["emote-superrun", 6.27],
    "Super Punch": ["emote-superpunch", 3.75],
    "Sumo Fight": ["emote-sumo", 10.87],
    "Thumb Suck": ["emote-suckthumb", 4.19],
    "Splits Drop": ["emote-splitsdrop", 4.47],
    "Snowball Fight": ["emote-snowball", 5.23],
    "Snow Angel": ["emote-snowangel", 6.22],
    "Shy": ["emote-shy", 4.48],
    "Secret Handshake": ["emote-secrethandshake", 3.88],
    "Sad": ["emote-sad", 5.41],
    "Rope Pull": ["emote-ropepull", 8.77],
    "Roll": ["emote-roll", 3.56],
    "Rofl": ["emote-rofl", 6.31],
    "Robot": ["emote-robot", 7.61],
    "Rainbow": ["emote-rainbow", 2.81],
    "Kawaii": ["dance-kawai", 10.29],
    "Scritchy": ["idle-wild", 26.42],
    "Ice Skating": ["emote-iceskating", 7.3],
    "Surprise Big": ["emote-pose6", 5.38],
    "Bashful Blush": ["emote-shy2", 4.99],
    "Laid Back": ["sit-open", 20.0],
    "Flirty Wink": ["emote-pose1", 2.83],
    "Proposing": ["emote-proposing", 4.28],
    "Peekaboo": ["emote-peekaboo", 3.63],
    "Peace": ["emote-peace", 5.76],
    "Panic": ["emote-panic", 2.85],
    "No": ["emote-no", 2.7],
    "Ninja Run": ["emote-ninjarun", 4.75],
    "Night Fever": ["emote-nightfever", 5.49],
    "Monster Fail": ["emote-monster_fail", 4.63],
    "Model": ["emote-model", 6.49],
    "Flirty Wave": ["emote-lust", 4.66],
    "Level Up": ["emote-levelup", 6.05],
    "Amused": ["emote-laughing2", 5.06],
    "Laugh": ["emote-laughing", 1.13],
    "Super Kick": ["emote-kicking", 4.87],
    "Jump": ["emote-jumpb", 3.58],
    "Judo Chop": ["emote-judochop", 2.43],
    "Imaginary Jetpack": ["emote-jetpack", 16.76],
    "Hug Yourself": ["emote-hugyourself", 4.99],
    "Sweating": ["emote-hot", 4.35],
    "Hero Entrance": ["emote-hero", 5.0],
    "Hello": ["emote-hello", 2.73],
    "Headball": ["emote-headball", 10.07],
    "Harlem Shake": ["emote-harlemshake", 13.56],
    "Happy": ["emote-happy", 3.48],
    "Handstand": ["emote-handstand", 4.02],
    "Greedy": ["emote-greedy", 4.64],
    "Touch": ["dance-touch", 11.7],
    "Creepycute": ["emote-creepycute", 7.9],
    "Frustrated": ["emote-frustrated", 5.0],
    "Pose 10": ["emote-pose10", 3.99],
    "Tiktok 7": ["idle-dance-tiktok7", 15.0],
    "Repose": ["sit-relaxed", 29.89],
    "Star Gazing": ["emote-stargaze", 5.0],
    "Superpose": ["emote-superpose", 4.53],
    "Grave Dance": ["dance-weird", 21.56],
    "Celebration Step": ["emote-celebrationstep", 3.35],
    "Slap": ["emote-slap", 5.0],
    "Graceful": ["emote-graceful", 3.75],
    "Moonwalk": ["emote-gordonshuffle", 8.05],
    "Ghost Float": ["emote-ghost-idle", 19.57],
    "Gangnam Style": ["emote-gangnam", 7.28],
    "Frolic": ["emote-frollicking", 3.7],
    "Faint": ["emote-fainting", 18.42],
    "Clumsy": ["emote-fail2", 6.48],
    "Fall": ["emote-fail1", 5.62],
    "Face Palm": ["emote-exasperatedb", 2.72],
    "Exasperated": ["emote-exasperated", 2.37],
    "Shrink": ["emote-shrink", 5.0],
    "Elbow Bump": ["emote-elbowbump", 3.8],
    "Heart Fingers": ["emote-heartfingers", 4.0],
    "Heart Shape": ["emote-heartshape", 5.0],
    "Idle Sleep": ["idle-sleep", 15.0],
    "Hug": ["emote-hug", 5.0],
    "Eyeroll": ["emoji-eyeroll", 5.0],
    "Embarrassed": ["emote-embarrassed", 5.0],
    "Float": ["emote-float", 9.0],
    "Telekinesis": ["emote-telekinesis", 10.49],
    "Sexy Dance": ["dance-sexy", 10.0],
    "Puppet": ["emote-puppet", 5.0],
    "Swordfight": ["emote-swordfight", 5.91],
    "Fighter Idle": ["idle-fighter", 15.0],
    "Penguin Dance": ["dance-pinguin", 11.58],
    "Creepy Puppet": ["dance-creepypuppet", 6.42],
    "Ghost": ["emoji-ghost", 5.0],
    "Disco": ["emote-disco", 5.37],
    "Blast Off": ["emote-disappear", 6.2],
    "Faint Drop": ["emote-deathdrop", 3.76],
    "Collapse": ["emote-death2", 4.86],
    "Dont Start Now": ["dance-tiktok2", 10.39],
    "Revival": ["emote-death", 6.62],
    "Dab": ["emote-dab", 2.72],
    "Curtsy": ["emote-curtsy", 2.43],
    "Confused": ["emote-confused", 8.58],
    "Attention": ["emote-attention", 5.0],
    "Cold": ["emote-cold", 3.66],
    "Charging": ["emote-charging", 8.03],
    "Bunny Hop": ["emote-bunnyhop", 12.38],
    "Bow": ["emote-bow", 3.34],
    "Boo": ["emote-boo", 4.5],
    "Home Run": ["emote-baseball", 7.25],
    "Falling Apart": ["emote-apart", 4.81],
    "Thumbs Up": ["emoji-thumbsup", 2.7],
    "Point": ["emoji-there", 2.06],
    "Sneeze": ["emoji-sneeze", 3.0],
    "Smirk": ["emoji-smirking", 4.82],
    "Sick": ["emoji-sick", 5.07],
    "Gasp": ["emoji-scared", 3.01],
    "Punch": ["emoji-punch", 1.76],
    "Pray": ["emoji-pray", 4.5],
    "Stinky": ["emoji-poop", 4.8],
    "Naughty": ["emoji-naughty", 4.28],
    "Mind Blown": ["emoji-mind-blown", 2.4],
    "Lying": ["emoji-lying", 6.31],
    "Levitate": ["emoji-halo", 5.84],
    "Fireball Lunge": ["emoji-hadoken", 2.72],
    "Give Up": ["emoji-give-up", 5.41],
    "Tummy Ache": ["emoji-gagging", 5.5],
    "Flex": ["emoji-flex", 2.1],
    "Stunned": ["emoji-dizzy", 4.05],
    "Cursing": ["emoji-cursing", 2.38],
    "Sob": ["emoji-crying", 3.7],
    "Clap": ["emoji-clapping", 2.16],
    "Raise The Roof": ["emoji-celebrate", 3.41],
    "Arrogance": ["emoji-arrogance", 6.87],
    "Angry": ["emoji-angry", 5.76],
    "Vogue Hands": ["dance-voguehands", 10.0],
    "Savage Dance": ["dance-tiktok8", 10.94],
    "Yoga Flow": ["dance-spiritual", 10.0],
    "Smoothwalk": ["dance-smoothwalk", 10.0],
    "Ring On It": ["dance-singleladies", 10.0],
    "Lets Go Shopping": ["dance-shoppingcart", 4.32],
    "Russian Dance": ["dance-russian", 10.25],
    "Robotic": ["dance-robotic", 10.0],
    "Pennywise": ["dance-pennywise", 1.21],
    "Orange Juice Dance": ["dance-orangejustice", 10.0],
    "Rock Out": ["dance-metal", 10.0],
    "Karate": ["dance-martial-artist", 10.0],
    "Macarena": ["dance-macarena", 12.21],
    "Hands In The Air": ["dance-handsup", 10.0],
    "Floss": ["dance-floss", 10.0],
    "Duck Walk": ["dance-duckwalk", 10.0],
    "Breakdance": ["dance-breakdance", 10.0],
    "Kpop Dance": ["dance-blackpink", 7.15],
    "Sleigh": ["emote-sleigh", 11.33],
    "Ups": ["dance-aerobics", 10.0],
    "Maniac": ["emote-maniac", 4.91],
    "Energy Ball": ["emote-energyball", 7.58],
    "Singing": ["idle_singing", 10.26],
    "Frog": ["emote-frog", 14.55],
    "Cute": ["emote-cute", 6.17],
    "Tiktok Dance 9": ["dance-tiktok9", 11.89],
    "Tiktok 10": ["dance-tiktok10", 8.23],
    "Pose 7": ["emote-pose7", 4.66],
    "Pose 8": ["emote-pose8", 4.81],
    "Casual Dance": ["idle-dance-casual", 9.08],
    "Pose 3": ["emote-pose3", 5.11],
    "Ditzy Pose": ["emote-pose9", 4.58],
    "Pose 5": ["emote-pose5", 4.62],
    "Cutey": ["emote-cutey", 3.26],
    "Punk Guitar": ["emote-punkguitar", 9.37],
    "Zombie Run": ["emote-zombierun", 5.0],
    "Fashionista": ["emote-fashionista", 5.61],
    "Gravity": ["emote-gravity", 8.96],
    "Ice Cream Dance": ["dance-icecream", 14.77],
    "Wrong Dance": ["dance-wrong", 12.42],
    "Uwu": ["idle-uwu", 24.76],
    "Tiktok Dance 4": ["idle-dance-tiktok4", 15.5],
    "Anime Dance": ["dance-anime", 8.47],
    "Hyped": ["emote-hyped", 7.49],
    "Jinglebell": ["dance-jinglebell", 11.0],
    "Nervous": ["idle-nervous", 21.71],
    "Toilet": ["idle-toilet", 32.17],
    "Boxer": ["emote-boxer", 5.56],
    "Teleporting": ["emote-teleporting", 11.77],
    "Head Blowup": ["emote-headblowup", 11.67],
    "Air Guitar": ["idle-guitar", 13.23],
    "Dance Zombie": ["dance-zombie", 12.92],
    "This Is For You": ["emote-gift", 5.8],
    "Push It": ["dance-employee", 8.0],
    "Sweet Smooch": ["emote-kissing", 5.5],
    "Wop Dance": ["dance-tiktok11", 11.0],
    "Cute Salute": ["emote-cutesalute", 3.0],
    "At Attention": ["emote-salute", 3.0],
    "Launch": ["emote-launch", 5.0],
    "Fairy Twirl": ["emote-looping", 5.0],
    "Fairy Float": ["idle-floating", 15.0],
    "Swing Celebrate": ["emote-swing-celebrate", 5.0],
    "Swing Celebrate Idle": ["emote-swing-celebrate-idle", 5.0],
    "Swing Net 3": ["emote-swing-net-3", 5.0],
    "Swing Sneak Idle": ["emote-swing-sneak-Idle", 5.0],
    "Swing Net 2": ["emote-swing-net-2", 5.0],
    "Swing Net": ["emote-swing-net", 5.0],
    "Ballet Bliss": ["dance-ballet", 10.0],
    "Pure Heart": ["dance-true-heart", 10.0],
    "Mine Dance": ["dance-mine", 10.0],
    "Popular Vibe": ["dance-popularvibe", 10.0],
    "Swag Bounce": ["dance-swagbounce", 10.0],
    "Woah": ["dance-woah", 10.0],
    "Rest And Text": ["sit-idle-phone-text", 20.0],
    "Infinite Scroll": ["idle-laying-phone-texting", 15.0],
    "Yap Attack": ["idle-laying-phone-talking", 15.0],
    "The Fresh Step": ["dance-freshprince", 10.0],
    "Twerk It Out": ["dance-twerk", 10.0],
    "Knock Knock": ["emote-knocking-screen", 5.0],
    "Rifle Throw": ["emote-rifle-throw", 5.0],
    "Selfie Time": ["idle-phone-camera", 15.0],
    "Coolguy": ["emote-coolguy", 5.0],
    "Phone Talking": ["idle-phone-talking", 15.0],
    "Wait": ["dance-wait", 10.0],
    "Crouched": ["idle-crouched", 15.0],
    "Doomscroll": ["emote-phone", 5.0],
    "Tactical Flex": ["emote-rifle", 5.0],
    "Thought": ["emote-thought", 5.0],
    "Ignition Boost": ["hcc-jetpack", 10.0],
    "Mining": ["mining-mine", 6.0],
    "Mining Success": ["mining-success", 6.0],
    "Mining Fail": ["mining-fail", 6.0],
    "Landing A Fish": ["fishing-pull", 8.0],
    "Fishing Idle": ["fishing-idle", 8.0],
    "Cast": ["fishing-cast", 8.0],
    "We Have A Strike": ["fishing-pull-small", 8.0],
    "Tiktok 16": ["dance-tiktok16", 10.0],
    "Pose 13": ["emote-pose13", 5.0],
    "Pose 12": ["emote-pose12", 5.0],
    "Fruity Dance": ["dance-fruity", 10.0],
    "Pose 11": ["emote-pose11", 5.0],
    "Hipshake": ["dance-hipshake", 10.0],
    "Outfit 2": ["emote-outfit2", 5.0],
    "Cheerleader": ["dance-cheerleader", 10.0],
    "Outfit": ["emote-outfit", 5.0],
    "Tiktok 15": ["dance-tiktok15", 10.0],
    "Oops": ["emote-oops", 5.0],
}
